[package]
name = "wasm-player"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "cdylib", "rlib" ]

[dependencies]
wasm-bindgen = "0.2.86"

[dependencies.wasm-player]
git = "https://github.com/ChristianFischer/gb-emu.git"

